CREATE TABLE crawler_tasks (
    task_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '任务ID (由后端生成)',
    product_url VARCHAR(500) NOT NULL COMMENT '商品链接',
    status TINYINT DEFAULT 0 COMMENT '状态码: 0-等待, 1-进行中, 2-已完成, 3-失败',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='爬虫任务状态表';
